package dao;
// Generated 7 janv. 2017 23:16:38 by Hibernate Tools 4.3.1



/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private Integer id;
     private Client client;
     private Voiture voiture;
     private String nomImg;
     private byte[] contenu;

    public Image() {
    }

	
    public Image(String nomImg, byte[] contenu) {
        this.nomImg = nomImg;
        this.contenu = contenu;
    }
    public Image(Client client, Voiture voiture, String nomImg, byte[] contenu) {
       this.client = client;
       this.voiture = voiture;
       this.nomImg = nomImg;
       this.contenu = contenu;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Voiture getVoiture() {
        return this.voiture;
    }
    
    public void setVoiture(Voiture voiture) {
        this.voiture = voiture;
    }
    public String getNomImg() {
        return this.nomImg;
    }
    
    public void setNomImg(String nomImg) {
        this.nomImg = nomImg;
    }
    public byte[] getContenu() {
        return this.contenu;
    }
    
    public void setContenu(byte[] contenu) {
        this.contenu = contenu;
    }




}


